---

#############################
#############################
## JavaScript Linter rules ##
#############################
#############################

############
# Env Vars #
############
env:
  browser: true
  es6: true
  jest: false

###############
# Global Vars #
###############
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

###############
# Parser vars #
###############
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module

###########
# Plugins #
###########
#- '@typescript-eslint'
# https://www.npmjs.com/package/eslint-config-react-app#usage-outside-of-create-react-app
plugins:
  - '@typescript-eslint' 
  - 'flowtype@4.x' 
  - 'import@2.x' 
  - 'jsx-a11y@6.x' 
  - 'react@7.x' 
  - 'react-hooks@2.x'

#########
# Rules #
#########
rules: {}
