name: Code Formatting

on:
  pull_request:
  push:
    branches:
    - master
    - PoC4

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}

    - name: Prettify code
      uses: creyD/prettier_action@v2.2
      with:
        # This part is also where you can pass other options, for example:
        prettier_options: --check 'src/**/*.{js,jsx,ts,tsx}'